<div style="border-left: 3px solid #000; padding: 1px; padding-left: 10px; background: #F0FAFF; ">
<center><h1>Numpy</h1></center>

<p>Numpy is a Python library that provides efficient implementations of a large number of functions commonly used in scientific programming.  

<p>Consider trying to add two lists together in Python:
</div>

In [1]:
A = [1.0, 3, "hello, "]
B = [3.4, 3.2, "world"]

print([ a+B[i] for i,a in enumerate(A)])     # why can't we type A+B?

[4.4, 6.2, 'hello, world']


In [2]:
A+B

[1.0, 3, 'hello, ', 3.4, 3.2, 'world']

<div style="border-left: 3px solid #000; padding: 1px; padding-left: 10px; background: #F0FAFF; ">
<p> In order to add these two lists, Python has to first figure out which type of object is in each place in each list (note that there are *three* different types above).  It then has to figure out which method is appropriate for adding the two lists together.  In one case, above, it also must cast the type to another type so that the two can be added.
All of that takes computation time and in some cases space.  In addition, the objects themselves, being Python objects, are relatively complex.  Lists are designed to allow *flexibility*, not *efficiency*.

<p>Numpy is built around the numpy `array` object.  This object solves each of these problems. 

<ol>
<li>  Numpy objects are collections of a fixed, specific type. 
<li>  The types used in (most) numpy arrays are extremely simple types that the hardware itself uses and so do not come with the normal overhead of Python
</ol>

<p> In addition, the numpy array helps us to manipulate large data sets in important and convenient ways, by allowing us to index portions of the data in a manner appropriate to that data.

</div>

In [3]:
import numpy as np
from __future__ import print_function #clean up the print functions

<div style="border-left: 3px solid #000; padding: 1px; padding-left: 10px; background: #F0FAFF; ">
<p>A simple way to generate a numpy array is by casting a list.

</div>

In [4]:
# python list of integers
nums = [ 1, 2, 3, 4, 5 ]

# numpy array of integers
arr1 = np.array( nums )

print("arr1:",arr1)

arr1: [1 2 3 4 5]


In [5]:
arr1

array([1, 2, 3, 4, 5])

<div style="border-left: 3px solid #000; padding: 1px; padding-left: 8px; background: #F0FAFF; ">
<p> From the output, you can't tell that anything is different.  The important features of numpy arrays are under the hood.

<left><h2>numpy array operators</h2></left>






<p> Scalar addition:  This adds a constant to each element of the array.
</div>

In [6]:
arr2 = arr1 + 2

print("arr2:", arr2)

arr2: [3 4 5 6 7]


<div style="border-left: 3px solid #000; padding: 1px; padding-left: 10px; background: #F0FAFF; ">

<p>In contrast to lists, most common operations for numpy arrays act in an elementwise fashion.
<p>Arrays of the same size can be added together in an elementwise manner.

Elementwise addition:
</div>

In [7]:
arr3 = arr1 + arr2

print("arr3:", arr3)

arr3: [ 4  6  8 10 12]


<div style="border-left: 3px solid #000; padding: 1px; padding-left: 10px; background: #F0FAFF; ">
<p>Elementwise multiplication:

</div>

In [8]:
arr4 = arr1 * arr2

print("arr4:", arr4)

arr4: [ 3  8 15 24 35]


<div style="background: #DFF0D8; border-radius: 3px; padding: 10px;">
<p>**Exercise 4.2:**Create an array that represents the elementwise difference between two arrays.
</div>

In [9]:
#make arrays a and b 
c = a-b

NameError: name 'a' is not defined

<div style="background: #DFF0D8; border-radius: 3px; padding: 10px;">
<p>**Exercise 4.3:**  Divide one array by a second array in an elementwise fashion and save the result as a new array.  What happens if the second array contains a zero?
</div>

In [10]:
b[0] = 0
a/b

NameError: name 'b' is not defined

<div style="background: #DFF0D8; border-radius: 3px; padding: 10px;">
<p>**Exercise 4.4:**Make the two arrays different sizes - how does that affect the operations above?
</div>

<div style="border-left: 3px solid #000; padding: 1px; padding-left: 8px; background: #F0FAFF; ">
<left><h1>numpy array creation functions</h1></left>

<p>Use ```arange``` to create a sequence of values between two limits with defined step sizes

<p>Note that the end value is *excluded*

</div>

In [16]:
arr5 = np.arange(start=0, stop=10, step=1)

print("arr5:", arr5)

arr5: [0 1 2 3 4 5 6 7 8 9]


In [17]:
#use a larger step size
arr6 = np.arange(0, 10, 2)

print("arr6:", arr6)

arr6: [0 2 4 6 8]


<div style="border-left: 3px solid #000; padding: 1px; padding-left: 10px; background: #F0FAFF; ">
<p>Use ```linspace``` to create a sequence of values between two limits with a defined number of steps

<p>Note that the end value is *included*

</div>

In [18]:
arr7 = np.linspace(start=0.0, stop=1.0, num=5)

print("arr7:", arr7)

arr7: [ 0.    0.25  0.5   0.75  1.  ]


<div style="border-left: 3px solid #000; padding: 1px; padding-left: 10px; background: #F0FAFF; ">
<p>The arrays we have looked at so far have been 1-dimensional.  Quite often we work with data which is most meaningfully arranged in multiple-dimensions, e.g. images are arrays of data that are naturally described in terms of width and height, or a set of recordings from multiple neurons.

Multi-dimensional arrays can be created by using "lists of lists".
</div>

In [19]:
A = [[1,2],[3,4]]

array_A = np.array(A)
print(array_A)

[[1 2]
 [3 4]]


In [20]:
B = [[[1,2],[3,4],[5,6]],[[3,4],[5,6],[7,8]]]

array_B = np.array(B)
print(array_B)

[[[1 2]
  [3 4]
  [5 6]]

 [[3 4]
  [5 6]
  [7 8]]]


In [22]:
len(B)

2

<div style="border-left: 3px solid #000; padding: 1px; padding-left: 10px; background: #F0FAFF; ">
<p>numpy arrays have an attribute called "shape" that indicates how "long" the array is in each dimension.
</div>

In [23]:
print(array_A.shape)
print(array_B.shape)

(2, 2)
(2, 3, 2)


<div style="border-left: 3px solid #000; padding: 1px; padding-left: 10px; background: #F0FAFF; ">
<p>For real use cases, lists of lists is quite clumsy.

<p>One can use the functions ```zeros``` and ```ones``` to create an array of zeros or ones of a defined shape that are initially filled with zeros or ones, respectively.

</div>

In [2]:
import numpy as np

In [3]:
np.zeros?

In [24]:
# zeros, ones
zero_array = np.zeros((4,4))

print("zero_array:\n", zero_array) #\n is a newline character

zero_array:
 [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [25]:
one_array = np.ones((3,4,2))

print("one_array:\n", one_array)

one_array:
 [[[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]
  [ 1.  1.]]]


<div style="border-left: 3px solid #000; padding: 1px; padding-left: 10px; background: #F0FAFF; ">
<p>Use ```zeros_like``` and ```ones_like``` to create an array of zeros or ones that matches the shape of an existing array

</div>

In [26]:
another_one_array = np.ones_like(zero_array)

print("another_one_array:\n", another_one_array)

another_one_array:
 [[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


<div style="border-left: 3px solid #000; padding: 1px; padding-left: 10px; background: #F0FAFF; ">
<p>The `size` of an array is the total number of elements.  It will be the product of the elements of the `shape`.
</div>

In [27]:
A = np.array([[1,2,3],[4,5,6]])
print(A.size)

6


<div style="border-left: 3px solid #000; padding: 1px; padding-left: 10px; background: #F0FAFF; ">
<p>The ```random``` module contains functions for creating arrays with randomly distributed values. For instance, ```np.random.rand()``` gives uniformly distributed values between 0 and 1.
</div>

In [29]:
# random values in [0,1]
arr11 = np.random.rand(4,3)
print("arr11:\n", arr11)

arr11:
 [[ 0.89097437  0.1261113   0.20307232]
 [ 0.80110986  0.19142135  0.08342174]
 [ 0.70365701  0.92705501  0.52942545]
 [ 0.63076283  0.42543208  0.17444222]]


In [5]:
help(np.random.rand)

Help on built-in function rand:

rand(...)
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, should all be positive.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Notes
    -----
    This is a convenience function. If you want an interface that
    takes a shape-tuple as the first argument, refer to
    np.random.random_sample .
    
    Examples
    --------
    >>> np.random.rand(3,2)
    array([[ 0.14022471,  0.96360618],  #random
           [ 0.37601032,  0.25528411],  #random
           [ 0.49313049,  0.94909878]]) #random



<div style="background: #DFF0D8; border-radius: 3px; padding: 10px;">
<p>**Exercise 4.5:**  Create a 100x60 array of normally distributed values.  (Hint:  look at the functions available in np.random.)
</div>

(100, 60)

<div style="background: #DFF0D8; border-radius: 3px; padding: 10px;">
<p>**Exercise 4.6:**  Perform elementwise operations on the array generated above such that the mean is 5 and the standard deviation is 2.
</div>

In [12]:
arr2.mean(), arr2.std()

(5.003157094030378, 2.0079846633003084)

<div style="border-left: 3px solid #000; padding: 1px; padding-left: 8px; background: #F0FAFF; ">
<left><h1>Changing shape</h1></left>

<p>Reshape:  return a *new* array with a different shape.  The total `size` of the array must be compatible.  A common and convenient reshape operation is the transpose, which can be accessed with `.T`.

Resize:  change the shape of an array *in place*.  This does *not* return a new array.
</div>

In [30]:
# reshape
arr17 = np.arange(0,10,1)
print(arr17)

arr18 = arr17.reshape((2,5))            
print("\nreshaped:\n", arr18)

arr19 = arr18.T 
print("\ntransposed:\n", arr19)

print(arr17.shape)
arr17.resize((2,5))
print(arr17.shape)

[0 1 2 3 4 5 6 7 8 9]

reshaped:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

transposed:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
(10,)
(2, 5)


<div style="border-left: 3px solid #000; padding: 1px; padding-left: 8px; background: #F0FAFF; ">
<p>  In numpy, matrix multiplication is accomplished with the "dot" method, and not with the "*" operator
</div>

In [14]:
# dot product
I = np.eye(3,3)
Z = np.ones((3,3))
print(np.dot(I,Z),"\n")
print(I*Z)

(array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]]), '\n')
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


<div style="border-left: 3px solid #000; padding: 1px; padding-left: 8px; background: #F0FAFF; ">
<p>  Some array operations do not require that the shapes of the arrays be the same; if the rightmost dimensions of the the array agree, then any remaining dimensions will be "broadcast" across.  The documentation can help you if you are confused: http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html
</div>

In [32]:
# This works:
A = np.ones((3,4,4))
B =   np.ones((4,4))
print((A+B).shape)

# This doesn't:
A = np.ones((3,4,4))
B =   np.ones((4,3))
print((A+B).shape)


(3, 4, 4)


ValueError: operands could not be broadcast together with shapes (3,4,4) (4,3) 

<div style="background: #DFF0D8; border-radius: 3px; padding: 10px;">
<p>**Exercise 4.8:**  Create a small array of random numbers.  Use a method of the array to compute the sum of those numbers.  
</div>

<div style="background: #DFF0D8; border-radius: 3px; padding: 10px;">
<p>**Exercise 4.9:**  Create a small array of random numbers.  Replace one element in that array with ```np.nan``` (which stands for 'not a number').  Compute the sum of this array.
</div>

<div style="background: #DFF0D8; border-radius: 3px; padding: 10px;">
<p>**Exercise 4.10:**  Check out the list of mathematical operations here: http://docs.scipy.org/doc/numpy/reference/routines.math.html. Find a function that will allow you to sum over various dimensions while ignoring the ```np.nan```.
</div>

<div style="border-left: 3px solid #000; padding: 1px; padding-left: 8px; background: #F0FAFF; ">
<left><h1>array indexing</h1></left>

<p>Indexing can be used to identify and extract specific values from an array.  Remember that **Python indexes from 0!**

</div>

In [ ]:
arr20 = np.arange(0,10,1).reshape((2,5))
print("arr20:\n", arr20)

# remember, indexing is from zero!
print("\nvalue at location[0,2]\n", arr20[0,2])

<div style="border-left: 3px solid #000; padding: 1px; padding-left: 8px; background: #F0FAFF; ">
<p>  Similarly to lists, you can also use slicing to retrieve portions of an array.  Unlike lists, slicing an array gives you a new view into the array, it does *not* produce a copy.

<p>  You can also access elements of an array with "index arrays".  These can be arbitrary arrays that contain indices for each dimension of the array.  Each index array must be the same shape, and the returned array will have that shape.
</div>

In [ ]:
# grab an entire row or column
print("arr20:\n", arr20)
print("\nrow 1:\n", arr20[1,:])
print("\ncol 2:\n", arr20[:,2])
print("\n")
# index arrays with a 1-dimensional array
arr21 = np.arange(10)
index_array = np.array([[3,4,5],[7,9,8]])
print(arr21[index_array])

# index arrays with a 2-dimensional array
print("\n(row0 col2), (row0, col4) and (row1, col3):\n", arr20[(0, 0, 1),(2, 4, 3)])

<div style="border-left: 3px solid #000; padding: 1px; padding-left: 8px; background: #F0FAFF; ">

<h2>Boolean indexing</h2>

<p>Boolean comparisons with scalars will test the arrays elementwise against the scalar.  You can use this to generate an array indicating for which elements in an array that a condition is met.

<p>Furthermore, a boolean array can be used to index into another array of the same shape.  The return value will be a 1-dimensional array with the elements indicated as `True`.

</div>

In [ ]:
print("arr20:\n", arr20)

print("\nboolean array for values greater than 3:\n", arr20>3)

print("\napply the boolean array to the orignal array to return values > 3:\n", arr20[arr20>3])

<div style="border-left: 3px solid #000; padding: 1px; padding-left: 8px; background: #F0FAFF; ">

<p>The numpy ```where``` function will return the indices where a given condition is true.
<p>Numpy has a set of logical functions that allow for comparisons between different arrays elementwise.  The function for `and` is  ```logical_and```.  This can be used to next comparisons.

</div>

In [ ]:
print("arr20:\n", arr20)

print("\nindex array for values greater than 3 AND less than or equal to 5:\n", 
      np.where(np.logical_and(arr20>3,arr20<=5)))

print("\napply the index array to the orignal array to return values > 3 and <=5:\n", 
      arr20[np.where(np.logical_and(arr20>3,arr20<=5))])

<div style="background: #DFF0D8; border-radius: 3px; padding: 10px;">
<p>**Exercise 4.11:**

<p>Return all of the values of arr20 that are less than 2 or greater than 7

</div>

<div style="border-left: 3px solid #000; padding: 1px; padding-left: 8px; background: #F0FAFF; ">

<p>array masking

</div>

In [ ]:
arr21 = np.arange(0,10,1).reshape((2,5))
print("\noriginal array:\n", arr21)

# generate a logical mask of your array
mask = arr21 > 4
print("\nmask:\n", mask)

# now use it to modify the elements that match
arr21[mask] += 100
print("\nmasked array:\n", arr21)

<div style="border-left: 3px solid #000; padding: 1px; padding-left: 8px; background: #F0FAFF; ">

<h2>MATLAB gotchas</h2>

<p>Transitioning from MATLAB to python/numpy can be fun, but tricky. Here is a list of things to keep in mind:

<LI> Matlab indices start at "1"; python/numpy start at "0"
<LI> `For` loops, like MATLAB, are very slow in python, you should vectorize when possible.
<LI> In python, matrix multiplication is done with "dot", not "*"
<LI> Integer division is not automatically typecast to float for you.

<p> Check out http://mathesaurus.sourceforge.net/matlab-numpy.html for code examples help ease the transition

</div>

<div style="background: #DFF0D8; border-radius: 3px; padding: 10px;">
<left><h1>Exercises</h1></left>

</div>

<div style="background: #DFF0D8; border-radius: 3px; padding: 10px;">
<p>**Exercise 4.13:**

<p>Create a 1-d numpy array (call it ```ts``` for timestamps), with increasing integers from 3 to 300 (including 3 but not 300) with increment of 3, and print the array

</div>

<div style="background: #DFF0D8; border-radius: 3px; padding: 10px;">
<p>**Exercise 4.15:**

<p>add 0.5 to every element in ts which is larger than 200 and print ts

</div>

<div style="background: #DFF0D8; border-radius: 3px; padding: 10px;">
<p>**Exercise 4.17:**

<p>find the index of the element closest to the number 212.3, and print that index and print the element

</div>